# Transcriptomics Databases and Transcript Abundance

## About this chapter

1.  Questions
    -   How can I use the ENA and NCBI to download sequence reads for transcripts?
    -   What is the overall pipeline for estimating abundance of transcripts?
    -   How can I annotate an assembled prokaryotic genome?
2.  Objectives
    -   Download some reads identified in ENA using efficient tools
    -   Run the tools needed to estimate transcript abundances

## Interactive tutorial

The work in this course is provided as a combination of interactive tutorial and command-line tasks for you to run on your own machine. All the materials you need are referenced in the interactive tutorial.

::: {.callout-note}

  * Run the interactive tutorial here <a href="https://tsl-bioinformatics.shinyapps.io/transcriptome_dbs/"</a>

If you want to use the pre-prepared Colab instance, you can find that here:
<a href="https://colab.research.google.com/drive/1LJffmZ4yuzEjvtWp6Sj5tSibyTKJb_b1?usp=sharing"</a>
:::
