# Preface {.unnumbered}

The primary purpose of this course is to introduce you to databases that contain genome sequence data, transcriptome data and sequence structural data, and some of the tools that you can use to interact with them. Most of the material in this course will be web-based but some work will be via command lines.

## Three weeks of computational analysis can save you an hour of database searches

All scientists know well the value of the library and how getting up to speed with the literature and current knowledge will prevent you from wasting time in the lab testing (or rather re-testing) ideas that have already been tested. An analogous rule in bioinformatics is that databases contain data and results that have already been performed such that knowing about them and how to access them can save you great deal of effort. Knowing that you can just download some results can help you progress and develop your own unique analyses much more quickly. The trick therefore is simply to know what databases exist, what is in them and how to extract what you need from them.

In this short course we'll look at primary and secondary genomics and transcriptomic databases as well as looking at tools that can make downloading from them very straightforward. We'll also look at some databases and tools for examining protein structures.


## Prerequisites

### Knowledge prerequisites

The materials in this book assume that you already know how to make use of command line tools.

### Software prerequisites

You have two options to run the software for this course, you can run it in the pre-built Colab Document which you can access by clicking this [Link to Google Colab](https://colab.research.google.com/drive/1LJffmZ4yuzEjvtWp6Sj5tSibyTKJb_b1?usp=sharing)

You will need a Google account to use it. If you don't yet have one, or don't want to use your personal account for this perhaps you could sign up using your `@tsl.ac.uk` address.


Alternatively, you can install the tools yourself on your local machine, which means you need to install the following stuff:

-   [SRA Toolkit](https://github.com/ncbi/sra-tools/wiki/01.-Downloading-SRA-Toolkit)
-   [SPAdes](https://github.com/ablab/spades)
-   [prokka](https://github.com/tseemann/prokka)
-   [busco](https://busco.ezlab.org/busco_userguide.html)
-   [kallisto](https://pachterlab.github.io/kallisto/download)

Most can be installed using [bioconda](http://www.ddocent.com//bioconda/)
